-- Learning migration: run in the Supabase SQL Editor.
-- No auth.users foreign key is intentionally created for owner_id.
create table if not exists public.training_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.training_notes enable row level security;

revoke all on table public.training_notes from anon, authenticated;
revoke all on sequence public.training_notes_id_seq from anon, authenticated;

insert into public.training_notes (owner_id, title, content)
values
  (null, '과제', '실습용 가상 과제 기록'),
  (null, '포트폴리오', '실습용 가상 포트폴리오 기록'),
  (null, '아침 리추얼', '실습용 가상 리추얼 기록'),
  (null, '훈련 행정 자료', '실습용 가상 행정 기록');
